export const info = [
  "It is believed that <b>Hashim<b> was the first to institute the two caravan journeys of Quraysh, summer and winter (the journeys mentioned in Sura 106)",
  "<b>Abd Al-Muttalib<b> was the one who dug Zam Zam well for the second time after it disappeared",
  "The incident of the elephant (mentioned in Sura 105) happened <b>50 days<b> before the birth of our prophet Muhammad (Peace Be Upon Him)",
  "The name of the king that led the army trying to demolish Al Kaabah was <b>Abrahah<b>",
  "Our prophet Muhammad was born into the best 2 clans of Arabs: <b>Hashimite and Zohra clans<b>",
  "The short Family Linage of the prophet Muhammad (Peace Be Upon Him) is: <b>Muhammad Bin Abdullah Bin Abd Al-Muttalib Bin Hashim Bin Abd Manaaf Bin Qusay<b>",
  "<b>Abdullah<b>, the father of our prophet Muhammad (Peace Be Upon Him) died in <b>Yathrib<b> (the old name of Al Madina Al Munawara)",
  "Our prophet Muhammad (Peace Be Upon Him) was born on the <b>12th of Rabi' Al Awal<b> in the Year of the Elephant (570 AD)",
  "The name of our prophet Muhammad (Peace Be Upon Him) is derived from the Arabic word “حمّد” or “Hammada” which means the praiseworthy or glorified",
  "Our prophet Muhammad (Peace Be Upon Him) was Nursed/Breastfed by: his Mother <b>Amina Bint Wahb<b>, and then by <b>Thuwaybah - a servant of Abu Lahab<b>, and then by <b>Halimah al-Sa'adiya<b>",
  "The name of the Nanny of the prophet Muhammad (Peace Be Upon Him) was: <b>Baraka<b> commonly known as <b>Umm Ayman<b>",
  "<b>Amina<b> the mother of our prophet Muhammad (Peace Be Upon Him) died when he was <b>6 years old<b>, and was buried in <b>Al Abuaa'<b> (name of a place between Makkah and Madina)",
  "<b>Abd Al-Muttalib<b> the grandfather of our prophet Muhammad (Peace Be Upon Him) died when he was <b>8 years old<b>",
  "The trustworthy character of our prophet Muhammad (Peace Be Upon Him) acquired him the nicknames of: <b>Al-Sadiq<b> meaning 'truthful' and <b>Al-Amin<b> meaning 'faithful', 'trustworthy' among Makkah People",
  "Our prophet Muhammad (Peace Be Upon Him) married his wife <b>Khadija Bint Khuwaylid<b> (Radi Allahu Anha) when he was <b>25 years old<b> and she was <b>40 years old<b>",
];
