export const info = [
  "It is believed that <b>Hashim<b> was the first to institute the two caravan journeys of Quraysh, summer and winter (the journeys mentioned in Sura 106)",
  "<b>Abd Al-Muttalib<b> was the one who dug Zam Zam well for the second time after it disappeared",
  "The incident of the elephant (mentioned in Sura 105) happened <b>50 days<b> before the birth of our Prophet Muhammad (Peace Be Upon Him)",
  "The name of the king that led the army trying to demolish Al Kaabah was <b>Abrahah<b>",
  "Our Prophet Muhammad was born into the best 2 clans of Arabs: <b>Hashimite and Zohra clans<b>",
  "The short Family Linage of the Prophet Muhammad (Peace Be Upon Him) is: <b>Muhammad Bin Abdullah Bin Abd Al-Muttalib Bin Hashim Bin Abd Manaaf Bin Qusay<b>",
  "<b>Abdullah<b>, the father of our Prophet Muhammad (Peace Be Upon Him) died in <b>Yathrib<b> (the old name of Al Madina Al Munawara)",
  "Our Prophet Muhammad (Peace Be Upon Him) was born on the <b>12th of Rabi' Al Awal<b> in the Year of the Elephant (570 AD)",
  "The name of our Prophet Muhammad (Peace Be Upon Him) is derived from the Arabic word “حمّد” or “Hammada” which means the praiseworthy or glorified",
  "Our Prophet Muhammad (Peace Be Upon Him) was Nursed/Breastfed by: his Mother <b>Amina Bint Wahb<b>, and then by <b>Thuwaybah - a servant of Abu Lahab<b>, and then by <b>Halimah al-Sa'adiya<b>",
  "The name of the Nanny of the Prophet Muhammad (Peace Be Upon Him) was: <b>Baraka<b> commonly known as <b>Umm Ayman<b>",
  "<b>Amina<b> the mother of our Prophet Muhammad (Peace Be Upon Him) died when he was <b>6 years old<b>, and was buried in <b>Al Abuaa'<b> (name of a place between Makkah and Madina)",
  "<b>Abd Al-Muttalib<b> the grandfather of our Prophet Muhammad (Peace Be Upon Him) died when he was <b>8 years old<b>",
  "The trustworthy character of our Prophet Muhammad (Peace Be Upon Him) acquired him the nicknames of: <b>Al-Sadiq<b> meaning 'truthful' and <b>Al-Amin<b> meaning 'faithful', 'trustworthy' among Makkah People",
  "Our Prophet Muhammad (Peace Be Upon Him) married his wife <b>Khadija Bint Khuwaylid<b> (Radi Allahu Anha) when he was <b>25 years old<b> and she was <b>40 years old<b>",
  "Our Prophet Muhammad (Peace Be Upon Him) had 6 children from his wife Khadija (Radi Allahu Anha), and they are: <b>Al Qasim<b>, and then <b>Zainab<b>, and then <b>Ruqayya<b>, and then <b>Umm Kulthum<b>, and then <b>Fatima<b> and lastly <b>Abdullah<b> (Radi Allahu Anhum)",
  "All the children of the Prophet Muhammad (Peace Be Upon Him) were from Khadija except for <b>Ibrahim<b> who was from <b>Maria Al-Qibtiyya<b> (Radi Allah Anhum)",
  "All the children of the Prophet Muhammad (Peace Be Upon Him) died while he was alive except for <b>Fatima<b> (Radi Allah Anhum)",
  "<b>Fatima<b> (Radi Allahu Anha) died following the death of her father (our Prophet Muhammad Peace Be Upon Him) by <b>6 months<b>",
  "The daughter most dear to our Prophet's (Peace Be Upon Him) heart was <b>Fatima<b> (Radi Allahu Anha)",
  "Our Prophet Muhammad (Peace Be Upon Him) Participated in the rebuilding of Al Kaabah when he was <b>35<b> years of age",
  "Our Prophet Muhammad (Peace Be Upon Him) received the first revelation when he was <b>40<b> years of age",
  "The first revelation took place during the month of <b>Ramadan<b> when he was meditating in the <b>Cave of Hira<b>",
  "The Cave of Hira is located in one of Makkah mountains named <b>Al Noor Mountain<b>",
  "The first Surah to be revealed to the Prophet was <b>Surat Al-'Alaq<b> (Surah No. 96) that starts with the word <b>Iqraa'<b> (Meaning Read in Arabic)",
  "Jibreel (Peace Be Upon Him) sometimes used to come to our Prophet Muhammad (Peace be Upon him) in the Image of one of the Sahaba's named: <b>Dihya Al-Kalbi<b> (Radi Allahu Anhu)",
  "Da'wa of our Prophet Muhammad (Peace Be Upon Him) can be segregated into 2 main stages: <b>Da'wa in Makkah<b> (for 13 years), <b>Da'wa in Madina<b> (for 10 years)",
  "The first woman to become a Muslim was the wife of our Prophet Muhammad (Peace be upon him) <b>Khadija<b> (Radi Allahu Anha)",
  "The first man to become a Muslim was the dearest friend of our Prophet Muhammad (Peace be upon him) <b>Abu Bakr Al-Siddiq<b> (Radi Allahu Anhu)",
  "The first boy to become a Muslim was the cousin of our Prophet Muhammad (Peace be upon him) <b>Ali Bin Abi Talib<b> (Radi Allahu Anhu)",
];
